--- #YAML:1.0
name: Class-MethodFilter
version: 0.01
author:
  - Matt S Trout <mstrout@cpan.org>
abstract: add filters to class methods
license: perl
provides:
  Class::MethodFilter:
    file: lib/Class/MethodFilter.pm
    version: 0.01
generated_by: Module::Build version 0.24
